// types
import type { Metadata, Viewport } from "next";
// styles
import localFont from "next/font/local";
import "./globals.css";
import "../../public/fonts/icons/icons.css";
import "../../public/fonts/neon/Neon.font.css";
import "swiper/css";
import "swiper/css/parallax";
// providers
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ScrollSmoother } from "@/components/common/ScrollSmoother";
import { Header } from "@/components/layouts/Header";
import { Footer } from "@/components/layouts/Footer";
import { TopLoader } from "@/components/common/TopLoader";
import { SparklesCore } from "@/components/common/Particles/Particles";

export const montserratFont = localFont({
  src: [
    {
      path: "../../public/fonts/montserrat/Montserrat-Light.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/montserrat/Montserrat-Regular.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/montserrat/Montserrat-Medium.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/montserrat/Montserrat-SemiBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/montserrat/Montserrat-Bold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  weight: "500",
  adjustFontFallback: "Arial",
});

export const metadata: Metadata = {
  title: "Spexup",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  maximumScale: 1,
  initialScale: 1,
  colorScheme: "dark",
  themeColor: "var(--primary)",
};
export const revalidate = 0;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserratFont.className}>
        <ThemeProvider>
          <TopLoader />
          <ScrollSmoother />
          <Header />
          <SparklesCore />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
